name: Docs and ReDoc
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
 
  build_docs:
    runs-on: ubuntu-latest
 
    steps:
    - name: Prerequisites
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        sudo chmod +x .github/workflows/build_docs_and_redoc.sh
        pip install --editable git+https://github.com/ebisu-flashcards/flashcards-core.git#egg=flashcards_core
        pip install --editable .[dev]
      shell: bash
 
    - name: Build ReDoc and update Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ".github/workflows/build_docs_and_redoc.sh"
      shell: bash
